/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/applixTheme.ts
 * Command: astryx theme build src/themes/applixTheme.ts
 * CLI: @astryxdesign/cli@0.6.5
 * Core: @astryxdesign/core@0.6.5
 */

/// <reference path="./applix.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const applixTheme: DefinedTheme;
